# Generated by Django 4.1.7 on 2023-11-11 09:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=12)),
                ('street_address', models.CharField(max_length=100)),
                ('companyLogo_path', models.ImageField(default=None, upload_to='vendor_img/')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.city')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('end_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('total_workhand', models.IntegerField(default=11)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('street_address', models.CharField(max_length=250)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.city')),
                ('company_id', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='event_data.company')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Workhand_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workhand_category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Workhand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=12)),
                ('street_address', models.CharField(max_length=100)),
                ('profilePic_path', models.ImageField(default=None, upload_to='user_profile_img/')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Workhand_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.workhand_category')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.city')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.state')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_img/')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_date', models.DateField(default=datetime.datetime.now)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.company')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.event')),
                ('workhand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.workhand')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('feedback_date', models.DateField(default=datetime.datetime.now)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.event')),
                ('workhand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.workhand')),
            ],
        ),
        migrations.CreateModel(
            name='Event_workhand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_workhand', models.IntegerField(default=11)),
                ('Workhand_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.workhand_category')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.event')),
            ],
        ),
        migrations.CreateModel(
            name='Event_subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_subcategory_name', models.CharField(max_length=100)),
                ('Event_Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.event_category')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(default=datetime.datetime.now)),
                ('registration_status', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.company')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.event')),
                ('workhand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.workhand')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_category_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='event_data.event_category'),
        ),
        migrations.AddField(
            model_name='event',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.state'),
        ),
        migrations.AddField(
            model_name='company',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.state'),
        ),
    ]
