# Generated by Django 4.1.7 on 2023-08-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='boy',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='events',
            name='girls',
            field=models.IntegerField(default=None),
        ),
    ]
