# Generated by Django 4.1.7 on 2023-11-24 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0002_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_subcategory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_data.event_subcategory'),
        ),
    ]
