# Generated by Django 4.1.7 on 2023-08-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0002_events_boy_events_girls'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='both',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='boy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='girls',
            field=models.IntegerField(default=0),
        ),
    ]
