# Generated by Django 4.1.7 on 2023-08-15 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0003_events_both_alter_events_boy_alter_events_girls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
