# Generated by Django 4.1.7 on 2023-11-28 18:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_data', '0005_alter_company_companylogo_path_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='profile_pics',
        ),
    ]
