# Generated by Django 4.1.7 on 2023-08-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_provider',
            name='profile_img',
            field=models.ImageField(default=None, upload_to='user_profile_img'),
        ),
    ]
