# Generated by Django 4.1.7 on 2023-08-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0006_service_provider_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='service_provider',
            name='city',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='service_provider',
            name='state',
            field=models.CharField(max_length=65),
        ),
    ]
