# Generated by Django 4.1.7 on 2023-11-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0006_rename_profile_profile_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyLogo_path',
            field=models.ImageField(default='default.jpg', upload_to='vendor_img/'),
        ),
        migrations.AlterField(
            model_name='workhand',
            name='profilePic_path',
            field=models.ImageField(default='default.jpg', upload_to='user_profile_img/'),
        ),
    ]
