# Generated by Django 4.1.7 on 2023-08-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0007_alter_company_city_alter_company_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='User',
        ),
        migrations.RemoveField(
            model_name='events',
            name='address',
        ),
        migrations.RemoveField(
            model_name='events',
            name='category',
        ),
        migrations.RemoveField(
            model_name='events',
            name='company',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='company',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='event',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='service_man',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='User',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='company',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='event',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='workers',
        ),
        migrations.RemoveField(
            model_name='service_provider',
            name='User',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='company',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.DeleteModel(
            name='Registrations',
        ),
        migrations.DeleteModel(
            name='Service_provider',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
