# Generated by Django 4.1.7 on 2023-11-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0007_alter_company_companylogo_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyLogo_path',
            field=models.ImageField(default='default.jpg', upload_to='profile_img/'),
        ),
        migrations.AlterField(
            model_name='workhand',
            name='profilePic_path',
            field=models.ImageField(default='default.jpg', upload_to='profile_img/'),
        ),
    ]
