# Generated by Django 4.1.7 on 2023-08-18 16:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_data', '0008_remove_company_user_remove_events_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=65)),
                ('state', models.CharField(max_length=65)),
                ('image', models.ImageField(default=None, upload_to='vendor_img')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('end_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('workers_needed', models.IntegerField(default=1)),
                ('boy', models.IntegerField(default=0)),
                ('girls', models.IntegerField(default=0)),
                ('both', models.IntegerField(default=0)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='event_data.address')),
                ('category', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='event_data.category')),
                ('company', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='event_data.company')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=65)),
                ('state', models.CharField(max_length=65)),
                ('profile_img', models.ImageField(default=None, upload_to='user_profile_img')),
                ('special_skill', models.CharField(default=None, max_length=50)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('company', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='event_data.company')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.events')),
                ('workers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.service_provider')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_img')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('company', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='event_data.company')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.events')),
                ('service_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_data.service_provider')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='event_data.city'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='event_data.state'),
        ),
    ]
