# Generated by Django 4.1.7 on 2023-12-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0008_alter_company_companylogo_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.AddField(
            model_name='event_workhand',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyLogo_path',
            field=models.ImageField(default='default.jpg', upload_to='company_img/'),
        ),
        migrations.AlterField(
            model_name='workhand',
            name='profilePic_path',
            field=models.ImageField(default='default.jpg', upload_to='workhand_img/'),
        ),
    ]
