# Generated by Django 4.1.7 on 2023-12-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0009_remove_event_price_event_workhand_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='street_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workhand',
            name='street_address',
            field=models.CharField(max_length=200),
        ),
    ]
