# Generated by Django 4.1.7 on 2023-12-14 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0010_alter_company_street_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registrations',
            name='workhand_categoty_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event_data.workhand_category'),
        ),
    ]
