# Generated by Django 4.1.7 on 2023-08-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0011_alter_company_image_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_img/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_img/'),
        ),
        migrations.AlterField(
            model_name='service_provider',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_img/'),
        ),
    ]
