# Generated by Django 4.1.7 on 2023-12-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0013_alter_event_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
