# Generated by Django 4.1.7 on 2023-12-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0015_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
