# Generated by Django 4.1.7 on 2023-12-23 09:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0017_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
