# Generated by Django 4.1.7 on 2023-09-01 08:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_data', '0017_alter_company_image_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_provider',
            new_name='Workhand',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='service_man',
            new_name='workhand',
        ),
        migrations.RenameField(
            model_name='registrations',
            old_name='workers',
            new_name='workhand',
        ),
    ]
