# Generated by Django 4.1.7 on 2023-09-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0018_rename_service_provider_workhand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
