# Generated by Django 4.1.7 on 2023-12-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0018_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
