# Generated by Django 4.1.7 on 2023-09-07 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0019_rename_name_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
