# Generated by Django 4.1.7 on 2023-09-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0020_alter_registrations_registration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workhand_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workhand_category', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Event_Category',
        ),
        migrations.RenameField(
            model_name='event_category',
            old_name='category',
            new_name='event_category',
        ),
    ]
