# Generated by Django 4.1.7 on 2023-09-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0021_workhand_category_rename_category_event_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='type_of_workhand',
            field=models.ManyToManyField(to='event_data.workhand_category'),
        ),
    ]
