# Generated by Django 4.1.7 on 2023-12-29 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0021_remove_event_registrations_workhand_categoty_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registrations',
            name='payment_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='event_registrations',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
