# Generated by Django 4.1.7 on 2023-11-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0022_events_type_of_workhand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='both',
        ),
        migrations.RemoveField(
            model_name='events',
            name='boy',
        ),
        migrations.RemoveField(
            model_name='events',
            name='girls',
        ),
    ]
