# Generated by Django 4.1.7 on 2024-01-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0022_event_registrations_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registrations',
            name='rating',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, max_length=100),
        ),
    ]
