# Generated by Django 4.1.7 on 2024-01-19 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0027_alter_workhand_avg_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workhand',
            name='avg_rate',
        ),
        migrations.AddField(
            model_name='workhand',
            name='avg_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
