# Generated by Django 4.1.7 on 2024-01-19 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0028_remove_workhand_avg_rate_workhand_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhand',
            name='avg_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
