# Generated by Django 4.1.7 on 2024-02-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0032_alter_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhand',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
