# Generated by Django 4.1.7 on 2024-02-10 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_data', '0033_workhand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhand',
            name='avg_rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
